update=Friday, September 27, 2013 03:42:32 PM
last_client=pcbnew
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0
PadSizeH=0.75
PadSizeV=2.65
PcbTextSizeV=1
PcbTextSizeH=1
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[pcbnew/libraries]
LibDir=
LibName1=/Users/paretech/Dropbox/Watson/watson
LibName2=smd_transistors
