% Plot measurement data stored in ASCII format using
% save(filename, ..., format='ascii').

% clear

%% Load and Create Data
d1 = struct( ...
    'dat', {load('meas_20140402.txt')}, ...
    'frq', {[10e6, 10.7e6, 100e6, 500e6]}, ...
    'pwr', {-120:.5:16}, ...
    'leg', {{'10 MHz' '10.7 MHz' '100 MHz' '500 MHz'}}, ...
    'gxt', {'Log Response'}, ...
    'xlb', {'Input Level (dBm)'}, ...
    'ylb', {'Output Voltage (V)'} ...
    );

close all

hFigure = figure('Units', 'pixels');
hAxes   = axes();

hFTitle = title (d1.gxt           );
hXLabel = xlabel(d1.xlb           );
hYLabel = ylabel(d1.ylb           );

hold on; grid on;

axis(hAxes, [d1.pwr(1) d1.pwr(end) floor(min(d1.dat(:))) ceil(max(d1.dat(:)))]);

ph = plot(hAxes, d1.pwr'*ones(1,length(d1.frq)), d1.dat');
set(ph, 'LineWidth', 2.0);

hLegend = legend(d1.leg, 'Location', 'NorthWest');

set( hAxes, ...
    'FontName'   , 'Helvetica' );
set([hFTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica');
set([hLegend, hAxes], ...
    'FontSize'   , 12);
set(hLegend, ...
    'EdgeColor', [.3 .3 .3]);
set([hXLabel, hYLabel], ...
    'FontSize'   , 12          );
set( hFTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(hAxes, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:.5:5, ...
  'LineWidth'   , 1         );

%% Build Log Conformance Plot

clear; close all;

dat = load('meas_20140402.txt');

x  = -120:.5:16;
y1 = dat(2,:); % Measured output Voltage at 10.7 MHz

w = double(x>-70 & x<-10);

linfit = LinearModel.fit(x, y1, 'linear','Weights', w);

m = double(linfit.Coefficients(2,1));
b = double(linfit.Coefficients(1,1));

y2 = m*x + b;   % Linear Approximation.

db_err = (y2-y1)/m; % 10.7 

% ===================================

hFigure = figure('Units', 'pixels');
hAxes   = axes();

hFTitle = title ('Logarithmic Conformance at 10.7 MHz');
hXLabel = xlabel('Input Level (dBm)');
hYLabel = ylabel('Error (dB)');

hold on; grid on;

y_upper = 4;
y_lower = -4;
x_upper = x(find(round(db_err)==y_upper, 1,'first')) + 1;
x_lower = x(find(round(db_err)==y_lower, 1,'last')) - 1;

axis(hAxes, [x_lower x_upper y_lower y_upper]);

hp = plot(x, db_err);

set([hp], ...
    'LineWidth', 2.0 ...
);

set( hAxes, ...
    'FontName'   , 'Helvetica' );

set([hFTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica');

set([hAxes], ...
    'FontSize'   , 12);

set([hXLabel, hYLabel], ...
    'FontSize', 12);

set( hFTitle, ...
    'FontSize'   , 12, ...
    'FontWeight' , 'bold' ...
);

set(hAxes, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , -4:1:4, ...
  'LineWidth'   , 1 ...
  );

