% Plot measurement data stored in ASCII format using
% save(filename, ..., format='ascii').

% clear

d1 = struct( ...
    'dat', {load('meas_20140402.txt')}, ...
    'frq', {[10e6, 10.7e6, 100e6, 500e6]}, ...
    'pwr', {-120:.5:16}, ...
    'leg', {{'10 MHz' '10.7 MHz' '100 MHz' '500 MHz'}}, ...
    'gxt', {'Input vs. Output with 50 Ohm Load'}, ...
    'xlb', {'Input Power (dB)'}, ...
    'ylb', {'Output Voltage (v)'} ...
    );

close all





hFigure = figure('Units', 'pixels');
hAxes   = axes();

hFTitle = title (d1.gxt           );
hXLabel = xlabel(d1.xlb           );
hYLabel = ylabel(d1.ylb           );

hold on; grid on;

axis(hAxes, [d1.pwr(1) d1.pwr(end) floor(min(d1.dat(:))) ceil(max(d1.dat(:)))]);

ph = plot(hAxes, d1.pwr'*ones(1,length(d1.frq)), d1.dat');
set(ph, 'LineWidth', 2.0);

hLegend = legend(d1.leg, 'Location', 'NorthWest');

set( hAxes, ...
    'FontName'   , 'Helvetica' );
set([hFTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica');
set([hLegend, hAxes], ...
    'FontSize'   , 12           );
set([hXLabel, hYLabel], ...
    'FontSize'   , 12          );
set( hFTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(hAxes, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:.5:5, ...
  'LineWidth'   , 1         );